# rebind prefix key
# unbind C-b
# set-option -g prefix C-y
# allow sending Ctrl+a to other apps by pressing it twice
bind C-b send-prefix

# rebind copy key
# bind C-v copy-mode

# set vi-mode copy key
setw -g mode-keys vi

# vi-mode pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# reload shortcut
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# vi-mode copy keys
# begin selection
bind-key -T copy-mode-vi v send-keys -X begin-selection
# copy to clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# vi-mode resize keys
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
